### ISSUE TITLE
Relay switch control

### ISSUE THREAD

**Issue by lars18th** [fake-name/DSP-W215-Poller#1]
Hi,

Please, can you add support for remote control the relay switch?

I hate to use the Android/iOS app, and I like to control using some home automation platform.

**Comment by fake-name** [comment]
The interface I'm using for getting power data is read-only, unfortunately.

It could probably be done, but you'd have to spend a lot more time reversing the binary (and possibly implement a SOAP client for the plug). 

It's probably possible, but I spent some time poking around with SOAP libraries for python, and it looks like it'll be messy, at best.

I've also actually completely disabled the relays entirely in the DSP-W215 plugs I have too (I don't want a person on my network to be able to turn off my servers, which is what they monitor), so it's an area I don't have any interest in pursuing.

Maybe if I had more time.

Sorry.

**Comment by lars18th** [comment]
Ok, I hope some other project will include this function.
Thank you!
However, can you explain how to disable the relays in the DSP-W215?

**Comment by fake-name** [comment]
Disabling them is pretty simple, you just take it apart and solder a heavy gauge jumper across the relay terminals.

You could also completely remove the relay entirely, but I didn't bother with that.

**Comment by lars18th** [comment]
So, hardware hack! Ok.

Please, when you know about another project for remote control the relays, please, post about it.

Regards!
